In [2]:
import numpy as np

# Задание 1
1. Установить, какие произведения матриц  AB  и  BA  определены, и найти размерности полученных матриц:

а)  A  — матрица  4×2 ,  B  — матрица  4×2 ;

б)  A  — матрица  2×5 ,  B  — матрица  5×3 ;

в)  A  — матрица  8×3 ,  B  — матрица  3×8 ;

г)  A  — квадратная матрица  4×4 ,  B  — квадратная матрица  4×4 .

In [6]:
# a)
a = np.ones((4,2))
b = np.ones((4,2))
a.dot(b)
# число строк должно равняться числу столбцов, поэтому нельтзя перемножить

ValueError: shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)

In [11]:
# б)
a = np.ones((2,5))
b = np.ones((5,3))
a.dot(b).shape
# получается матрица 2x3

(2, 3)

In [14]:
# в)
# Начинаем с матриц с единицами
a = np.ones((8,3))
b = np.ones((3,8))
a.dot(b).shape
# получается матрица 8х8

(8, 8)

In [18]:
# г)
# Начинаем с матриц с единицами
a = np.ones((4,4))
b = np.ones((4,4))
a.dot(b).shape
# получается матрица 4х4

(4, 4)

# Задание 2.
 2.Найти сумму и произведение матриц 
$ A =
\begin{pmatrix}
    1 & -2\\ 
    3 & 0
\end{pmatrix}
$ и $
B = 
\begin{pmatrix}
    4 & -1\\ 
    0 & 5
\end{pmatrix} $.

In [31]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])
print(f'Сумма - \n {a + b}')
print(f'Произведение - \n {a.dot(b)}')

Сумма - 
 [[ 5 -3]
 [ 3  5]]
Произведение - 
 [[  4 -11]
 [ 12  -3]]


# Задание 3.
3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $ 3A - 2B + 4C $ для матриц 
$ A =
\begin{pmatrix}
    1 & 7\\ 
    3 & -6
\end{pmatrix} $, $ B =
\begin{pmatrix}
    0 & 5\\ 
    2 & -1
\end{pmatrix} $, $ C =
\begin{pmatrix}
    2 & -4\\ 
    1 & 1
\end{pmatrix} $.

$
3A - 2B + 4C
=
3\begin{bmatrix}
    1 & 7 \\
    3 & -6
\end{bmatrix}
-
2\begin{bmatrix}
    0 & 5 \\
    2 & -1
\end{bmatrix}
+
4\begin{bmatrix}
    2 & -4 \\
    1 & 1
\end{bmatrix}
=
\begin{bmatrix}
    (3 - 0 + 8) & (21 - 10 - 16) \\
    (9 - 4 + 4) & (-18 + 2 + 4)
\end{bmatrix}
=
\begin{bmatrix}
    11 & -5 \\
    9 & -12
\end{bmatrix}
$

In [34]:
a = np.array([[1, 7], [3, -6]])
b = np.array([[0, 5], [2, -1]])
c = np.array([[2, -4], [1, 1]])
print(3 * a - 2 * b + 4 * c)

[[ 11  -5]
 [  9 -12]]


# Задание 4.
Дана матрица
$ A =
\begin{pmatrix}
    4 & 1\\ 
    5 & -2\\ 
    2 & 3
\end{pmatrix} $. Вычислить $ A A^{T} $ и $ A^{T} A $.

$
A^T =
\begin{bmatrix}
    4 & 5 & 2 \\ 
    1 & -2 & 3
\end{bmatrix}
$ \
$
A A^T
=
\begin{bmatrix}
    4 & 1\\ 
    5 & -2\\ 
    2 & 3
\end{bmatrix}
\cdot
\begin{bmatrix}
    4 & 5 & 2 \\ 
    1 & -2 & 3
\end{bmatrix}
=
\begin{bmatrix}
    (16 + 1) & (20 - 2) & (8 + 3) \\ 
    (20 - 2) & (25 + 4) & (10 - 6) \\ 
    (8 + 3) & (10 - 6) & (4 + 9)
\end{bmatrix}
=
\begin{bmatrix}
    17 & 18 & 11 \\ 
    18 & 29 & 4 \\ 
    11 & 4 & 13
\end{bmatrix}
$ \
$
A^T A
=
\begin{bmatrix}
    4 & 5 & 2 \\ 
    1 & -2 & 3
\end{bmatrix}
\cdot
\begin{bmatrix}
    4 & 1\\ 
    5 & -2\\ 
    2 & 3
\end{bmatrix}
=
\begin{bmatrix}
    (16 + 25 + 4) & (4 - 10 + 6)  \\ 
    (4 - 10 + 6) & (1 + 4 + 9)
\end{bmatrix}
=
\begin{bmatrix}
    45 & 0 \\ 
    0 & 14
\end{bmatrix}
$



In [35]:
a = np.array([[4, 1], [5, -2], [2, 3]])

In [42]:
print(a.T)

[[ 4  5  2]
 [ 1 -2  3]]


In [43]:
print(a.dot(a.T))

[[17 18 11]
 [18 29  4]
 [11  4 13]]


In [44]:
print(a.T.dot(a))

[[45  0]
 [ 0 14]]
