In [2]:
import numpy as np

# Задание 1.
Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей:

$
A =
\begin{bmatrix}
    -1 & -6 \\ 
    2 & 6
\end{bmatrix}
$.

Решим характеристическое уравнение линейного оператора $ A $.

$
det(\begin{bmatrix}
    -1 - \lambda & -6 \\ 
    2 & 6 - \lambda
\end{bmatrix})
= 0
$

$
(\lambda - 6)(\lambda + 1) + 6 * 2 = \lambda^2 - 5\lambda - 6 + 12 = 0
$

$
\lambda^2 - 5\lambda + 6 = 0
$

$
\lambda = 2; 3
$

Найдем собственные векторы для обоих значений $ \lambda $, подставив их в уравнение для собственных векторов $ Ax = \lambda x $.

$ \lambda = 2 $:

$
\begin{bmatrix}
    -1 & -6 \\ 
    2 & 6
\end{bmatrix}
x
= 2x
\Rightarrow
\begin{bmatrix} -1x_1 \\ 2x_1 \end{bmatrix} + \begin{bmatrix} -6x_2 \\ 6x_2 \end{bmatrix} = \begin{bmatrix} 2x_1 \\ 2x_2 \end{bmatrix}
\Rightarrow
\begin{cases}
-x_1 - 6x_2 = 2x_1 \\
2x_1 + 6x_2 = 2x_2
\end{cases}
\Rightarrow
\begin{cases}
x_1 = -2x_2 \\
x_1 = -2x_2
\end{cases}
\Rightarrow
x_1 = -2x_2
$

Для $ \lambda = 2 $ собственный вектор $ \hat{v} = \begin{bmatrix} -2 \\ 1 \end{bmatrix} $. \
Если выразить это в формате единичного вектора, то $ \hat{v} = \begin{bmatrix} -\frac{2}{\sqrt{5}} \\ \frac{1}{\sqrt{5}} \end{bmatrix} = \begin{bmatrix} -0.8944 \\ 0.4472 \end{bmatrix} $.

$ \lambda = 3 $:

$
\begin{bmatrix}
    -1 & -6 \\ 
    2 & 6
\end{bmatrix}
x
= 3x
\Rightarrow
\begin{bmatrix} -1x_1 \\ 2x_1 \end{bmatrix} + \begin{bmatrix} -6x_2 \\ 6x_2 \end{bmatrix} = \begin{bmatrix} 3x_1 \\ 3x_2 \end{bmatrix}
\Rightarrow
\begin{cases}
-x_1 - 6x_2 = 3x_1 \\
2x_1 + 6x_2 = 3x_2
\end{cases}
\Rightarrow
\begin{cases}
2x_1 = -3x_2 \\
2x_1 = -3x_2
\end{cases}
\Rightarrow
x_1 = -\frac{3}{2}x_2
$

Для $ \lambda = 3 $ собственный вектор $ \hat{v} = \begin{bmatrix} \frac{3}{2} \\ -1 \end{bmatrix} $. \
Если выразить это в формате единичного вектора, то $ \hat{v} = \begin{bmatrix} \frac{5}{6} \\ -\frac{5}{9} \end{bmatrix} = \begin{bmatrix} 0.8333 \\ -0.5556 \end{bmatrix} $.

In [17]:
a = np.array([[-1, -6], [2, 6]])
np.linalg.eig(a)

(array([2., 3.]),
 array([[-0.89442719,  0.83205029],
        [ 0.4472136 , -0.5547002 ]]))

# Задание 2.
Дан оператор поворота на 180 градусов, задаваемый матрицей:

$
A =
\begin{bmatrix}
    -1 & 0\\ 
    0 & -1
\end{bmatrix}
$.

Показать, что __любой__ вектор является для него собственным.

Решим характеристическое уравнение линейного оператора $ A $.

$
det(\begin{bmatrix}
    -1 - \lambda & 0\\ 
    0 & -1 - \lambda
\end{bmatrix})
= 0
$

$
(-1 - \lambda)(-1 - \lambda) + 0 * 0 = (1 + \lambda)^2 = 0
$

$
\lambda = -1
$

Найдем собственные векторы для обоих значений $ \lambda $, подставив их в уравнение для собственных векторов $ Ax = \lambda x $.

$ \lambda = -1 $:

$
\begin{bmatrix}
    -1 & 0 \\ 
    0 & -1
\end{bmatrix}
x
= -x
\Rightarrow
\begin{bmatrix} -1x_1 \\ 0x_1 \end{bmatrix} + \begin{bmatrix} 0x_2 \\ -1x_2 \end{bmatrix} = \begin{bmatrix} -1x_1 \\ -1x_2 \end{bmatrix}
\Rightarrow
\begin{cases}
-x_1 = -x_1 \\
-x_2 = -x_2
\end{cases}
\Rightarrow
\begin{cases}
0x_1 = 0 \\
0x_2 = 0
\end{cases}
$

In [14]:
a = np.array([[-1, 0], [0, -1]])
np.linalg.eig(a)

(array([-1., -1.]),
 array([[1., 0.],
        [0., 1.]]))

# Задание 3.
Пусть линейный оператор задан матрицей:

$
A =
\begin{bmatrix}
    1 & 1 \\ 
    -1 & 3
\end{bmatrix}
$.

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

Проверим вектор $ x = (1, 1) $, подставив его в уравнение для собственных векторов $ Ax = \lambda x $.

$
\begin{bmatrix}
    1 & 1 \\ 
    -1 & 3
\end{bmatrix}
\begin{bmatrix} 1 \\ 1 \end{bmatrix}
=
\lambda \begin{bmatrix} 1 \\ 1 \end{bmatrix}
\Rightarrow
\begin{bmatrix} 1 \\ -1 \end{bmatrix}
+
\begin{bmatrix} 1 \\ 3 \end{bmatrix}
=
\begin{bmatrix} \lambda \\ \lambda \end{bmatrix}
\Rightarrow
\begin{cases}
    2 = \lambda \\
    2 = \lambda
\end{cases}
\Rightarrow
\lambda = 2
$

Получилось найти решение уравнения - $ \lambda = 2 $. Следовательно, вектор $ x = (1, 1) $ является собственным вектором линейного оператора $ A $. \
В виде единичного вектора - $ x = (\frac{1}{\sqrt{2}}, \frac{1}{\sqrt{2}}) = (0.7071, 0.7071) $

In [15]:
a = np.array([[1, 1], [-1, 3]])
np.linalg.eig(a)

(array([2.00000002, 1.99999998]),
 array([[ 0.70710677, -0.70710679],
        [ 0.70710679, -0.70710677]]))