## 1.1 Решить систему уравнений методом Гаусса


$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

Решение

Расширенная матрица системы
$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & 2\\ 
2 & 1 & -1 & 1\\ 
1 & 1 & -3 & 1\\ 
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4\\
\end{matrix}
\end{pmatrix}$$

Умножим первую стороку на 2:
$$\begin{pmatrix}
\left.\begin{matrix}
2 & 2 & -2 & -4\\ 
2 & 1 & -1 & 1\\ 
1 & 1 & -3 & 1\\ 
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4\\
\end{matrix}
\end{pmatrix}$$

Вычтем из второй строки первую: 
$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
0 & 1 & 3 & 5\\ 
1 & 1 & -3 & 1\\ 
\end{matrix}\right|
\begin{matrix}
0\\ 
2\\
4\\
\end{matrix}
\end{pmatrix}$$


Вычтем из третьей строки первую:
$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
0 & 1 & 3 & 5\\ 
0 & 0 & -2 & 3\\ 
\end{matrix}\right|
\begin{matrix}
0\\ 
2\\
4\\
\end{matrix}
\end{pmatrix}$$

$$\begin{cases}
    \displaystyle  x_3 = \frac{3x_4-4}{2} \\
    \displaystyle  x_2 = 2 - 5x_4 - \frac{3}{2}(3x_4-4)\\
    \displaystyle  x_1 = 2x_4 + \frac{3x_4-4}{2} - 2 + 5x_4 + \frac{3}{2}(3x_4-4)\\
    \end{cases} $$ где $x_4$ - любое 

## 1.2. Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

In [1]:
import numpy as np
from numpy import linalg

In [2]:
def sovmest(A, A_w):
    if linalg.matrix_rank(A) == linalg.matrix_rank(A_w):
        if linalg.matrix_rank(A) == A.shape[1]:
            print(f'Система совместна и имеет единственное решение')
        elif linalg.matrix_rank(A) < A.shape[1]:
            print(f'Система совместна и имеет бесконечное число решений') 
    elif linalg.matrix_rank(A) < linalg.matrix_rank(A_w):
        print(f'Система несовместна, решений нет')

In [3]:
A = np.array([[3, -1, 1],[2, -5, -3], [1, 1, -1]])
A_w = np.append(A, np.array([[4],[-17], [0]]), axis=1)
sovmest(A, A_w)

Система совместна и имеет единственное решение


In [4]:
A = np.array([[2, -4, 6],[1, -2, 3], [3, -6, 9]])
A_w = np.append(A, np.array([[1],[-2], [5]]), axis=1)
sovmest(A, A_w)

Система несовместна, решений нет


In [5]:
A = np.array([[1, 2, 5],[3, 1, -8]])
A_w = np.append(A, np.array([[4],[-2]]), axis=1)
sovmest(A, A_w)

Система совместна и имеет бесконечное число решений


## 1.3. Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

In [6]:
A = np.array([[1, 3, -2, 4],[0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
A_w = np.append(A, np.array([[3],[2],[4],[1]]), axis=1)
sovmest(A, A_w)

Система совместна и имеет единственное решение


## 2.1. Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

In [10]:
A = np.array([[1, -2,],[3, -4]])
s = np.array([[1, 7]])

A_1 = np.copy(A)
A_1[::,0] = s

A_2 = np.copy(A)
A_2[::,1] = s

x1 = round(linalg.det(A_1)/linalg.det(A), 4)
x2 = round(linalg.det(A_2)/linalg.det(A), 4)
print(f'Решение системы: \nx1 = {x1}, \nx2 = {x2}')

Решение системы: 
x1 = 5.0, 
x2 = 2.0


In [11]:
A = np.array([[2, -1, 5],[1, 1, -3], [2, 4, 1]])
s = np.array([[10, -2, 1]])

A_1 = np.copy(A)
A_1[::,0] = s

A_2 = np.copy(A)
A_2[::,1] = s

A_3 = np.copy(A)
A_3[::,2] = s

x1 = round(linalg.det(A_1)/linalg.det(A), 4)
x2 = round(linalg.det(A_2)/linalg.det(A), 4)
x3 = round(linalg.det(A_3)/linalg.det(A), 4)
print(f'Решение системы: \nx1 = {x1}, \nx2 = {x2}, \nx3 = {x3}')

Решение системы: 
x1 = 2.0, 
x2 = -1.0, 
x3 = 1.0


## 2.2*. Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

__2*.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

In [12]:
import scipy.linalg as la

In [13]:
def printMatrix ( matrix ): 
    for i in range ( len(matrix) ): 
        print('[', end='')
        for j in range ( len(matrix[i]) ): 
            print ("""{:7.2f}""".format(matrix[i][j]), end = "" ) 
        print(']\n')
    print ()

In [14]:
a = np.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]])
(P, L, U) = la.lu(a)
print('LU разложение:\n')
print('Матрица L:')
printMatrix(L)
print('Матрица U:')
printMatrix(U)

LU разложение:

Матрица L:
[   1.00   0.00   0.00]

[   0.67   1.00   0.00]

[   0.33   0.80   1.00]


Матрица U:
[   3.00  26.00  30.00]

[   0.00  -8.33  -8.00]

[   0.00   0.00   0.40]




In [15]:
a = np.array([[1, 1, 2, 4], [2, 5, 8, 9], [3, 18, 29, 18], [4, 22, 53, 33]])
(P, L, U) = la.lu(a)
print('LU разложение:\n')
print('Матрица L:')
printMatrix(L)
print('Матрица U:')
printMatrix(U)

LU разложение:

Матрица L:
[   1.00   0.00   0.00   0.00]

[   0.50   1.00   0.00   0.00]

[   0.75  -0.25   1.00   0.00]

[   0.25   0.75  -0.17   1.00]


Матрица U:
[   4.00  22.00  53.00  33.00]

[   0.00  -6.00 -18.50  -7.50]

[   0.00   0.00 -15.38  -8.62]

[   0.00   0.00   0.00  -0.10]


