In [4]:
import numpy as np
np.set_printoptions(precision=3)

## Тема 5 - Сингулярное разложение матриц

#### **1. Найти с помощью NumPy SVD для матрицы:**

$
\begin{pmatrix}
    1 & 2 & 0\\ 
    0 & 0 & 5\\ 
    3 & -4 & 2\\ 
    1 & 6 & 5\\ 
    0 & 1 & 0
\end{pmatrix}
$

In [5]:
A = np.array([
    [1, 2, 0],
    [0, 0, 5],
    [3, -4, 2],
    [1, 6, 5],
    [0, 1, 0],
])
print(f'Матрица A:\n{A}')

Матрица A:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


In [6]:
U, s, W = np.linalg.svd(A)

V = W.T

D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

In [7]:
print(f'Матрица D:\n{D}')

Матрица D:
[[8.825 0.    0.   ]
 [0.    6.141 0.   ]
 [0.    0.    2.533]
 [0.    0.    0.   ]
 [0.    0.    0.   ]]


In [8]:
print(f'Матрица U:\n{U}')

Матрица U:
[[ 0.171  0.157 -0.531 -0.799 -0.162]
 [ 0.393 -0.529  0.613 -0.434  0.031]
 [-0.144 -0.824 -0.524  0.14   0.074]
 [ 0.888  0.061 -0.247  0.378 -0.06 ]
 [ 0.081  0.108 -0.082 -0.105  0.982]]


In [9]:
print(np.dot(U.T, U))

[[ 1.000e+00  6.317e-17 -1.753e-16 -1.179e-16 -8.578e-18]
 [ 6.317e-17  1.000e+00  8.260e-17 -5.173e-17  3.827e-18]
 [-1.753e-16  8.260e-17  1.000e+00 -2.718e-16 -9.895e-17]
 [-1.179e-16 -5.173e-17 -2.718e-16  1.000e+00 -2.613e-17]
 [-8.578e-18  3.827e-18 -9.895e-17 -2.613e-17  1.000e+00]]


In [10]:
print(f'Матрица V:\n{V}')

Матрица V:
[[ 0.071 -0.367 -0.927]
 [ 0.717  0.665 -0.208]
 [ 0.693 -0.65   0.311]]


In [12]:
print(np.dot(V.T, V))

[[ 1.000e+00  1.233e-16  1.615e-17]
 [ 1.233e-16  1.000e+00 -2.212e-17]
 [ 1.615e-17 -2.212e-17  1.000e+00]]


In [13]:
print(np.dot(np.dot(U, D), V.T))

[[ 1.000e+00  2.000e+00  5.694e-16]
 [ 1.032e-15 -2.166e-15  5.000e+00]
 [ 3.000e+00 -4.000e+00  2.000e+00]
 [ 1.000e+00  6.000e+00  5.000e+00]
 [-1.059e-16  1.000e+00  5.529e-17]]


#### **2. Для матрицы из предыдущего задания найти:**
а) евклидову норму; \
б) норму Фробениуса.

а) Евклидова норма (равна первому элементу матрицы D)

In [14]:
norm_euclid = np.linalg.norm(A, ord=2)
print(round(norm_euclid, 6) == round(D[0, 0], 6))
norm_euclid

True


8.824868854820444

б) Норма Фробениуса (равна корню суммы квадратов элементов матрицы D)

In [32]:
norm_frob = np.linalg.norm(A, ord='fro')
print(round(norm_frob, 6) == round(np.sqrt(np.sum(D**2)), 6))
norm_frob

True


11.045361017187261